apiVersion: v1
kind: Service
metadata:
  name: backend-deploy
  namespace: backend
  labels:
    app: backend-deploy
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: backend-deploy